name: workflow
run-name: Start Server
on: [push]
jobs:
  job:
    name: job
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1.1.1
        with:
          bun-version: latest
      - run: bun spine.js